version: "3.8"

services:
  frontend:
    image: streamfront:latest

    ports:
      - "3000:3000"

    depends_on:
      - streamauth

      - streamstrem

    environment:
      - REACT_APP_API_URL=http://localhost:3000

  streamauth:
    image: streamauth:latest

    ports:
      - "3001:3001"

    environment:
      - NODE_ENV=dev

      - PORT=3000

      - MONGO_URI="mongodb+srv://utkarsh:Test%40123@streamingcluster.bw5rin1.mongodb.net/test"

  streamstrem:
    image: streamstream:latest

    ports:
      - "3002:3002"

    environment:
      - NODE_ENV=dev

      - PORT=3000

      - MONGO_URI="mongodb+srv://utkarsh:Test%40123@streamingcluster.bw5rin1.mongodb.net/test"
